// src/components/liquidityPool.jsx
import React from 'react';

const LiquidityPool = () => {
  return (
    <div>
      <h2 className="text-2xl font-bold mb-4">Liquidity Pool</h2>
      <h3 className="text-xl font-semibold mb-2">MicroVault Liquidity Pool</h3>
      <p className="mb-4">
        MicroVault features a custom liquidity pool that allows users to participate as suppliers or borrowers, supporting stablecoins, ETH, and a variety of crypto assets. Our liquidity pool operates as a decentralized market, governed by smart contract parameters that define collateralization thresholds, reserve configurations, and risk management measures.
      </p>
      <p className="mb-4">
        Suppliers provide liquidity into the pool, earning passive income through interest generated by loans.
      </p>
      <p className="mb-4">
        Borrowers can access liquidity from the pool by taking over-collateralized positions, allowing them to leverage assets for both flash loans and regular microloans.
      </p>
      <p className="mb-4">
        The governance-approved parameters for our liquidity pool are designed to ensure a balance between liquidity demands and risk control. Smart contracts handle all interactions seamlessly, including borrowing, repaying, and liquidations, without intermediaries. This approach enhances the transparency, security, and efficiency of financial activities within MicroVault.
      </p>
      <p className="mb-4">
        By offering a robust, decentralized pool with support for stablecoins and ETH, MicroVault provides a flexible platform for users seeking efficient access to liquidity or opportunities to earn yield on their assets.
      </p>
    </div>
  );
};

export default LiquidityPool;